version: "3.7"

services:
  app:
    build: .
    networks:
      - users-addresses-network
    container_name: app_users_addresses
    ports:
      - 3333:3333
    depends_on:
      - database
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules

  database:
    image: postgres:13
    container_name: database_users_addresses
    restart: always
    networks:
      - users-addresses-network
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=${USER_DB}
      - POSTGRES_PASSWORD=${PASSWORD_DB}
      - POSTGRES_DB=${NAME_DB}
    volumes:
      - pgdata:/data/postgres
networks:
  users-addresses-network:
    driver: bridge

volumes:
  node_modules:
  pgdata:
    driver: local
